"""Repository contract for authenticated MoodTune user data."""

from __future__ import annotations

from typing import Protocol


class UserRepository(Protocol):
    def create_user(self, user_id: str, values: dict[str, object]) -> dict[str, object]: ...
    def get_profile(self, user_id: str) -> dict[str, object] | None: ...
    def update_profile(self, user_id: str, values: dict[str, object]) -> dict[str, object]: ...
    def list_favorites(self, user_id: str) -> list[dict[str, object]]: ...
    def add_favorite(self, user_id: str, track: dict[str, object]) -> dict[str, object]: ...
    def remove_favorite(self, user_id: str, track_id: str) -> bool: ...
    def record_history(self, user_id: str, record: dict[str, object]) -> None: ...
    def list_history(self, user_id: str, limit: int | None = None) -> list[dict[str, object]]: ...
    def record_search(self, user_id: str | None, query: str, region: str | None) -> None: ...
    def list_recent_searches(self, user_id: str, limit: int) -> list[dict[str, object]]: ...
    def delete_recent_search(self, user_id: str, search_id: str) -> bool: ...
    def clear_recent_searches(self, user_id: str) -> int: ...
    def list_search_events(self, since: object) -> list[dict[str, object]]: ...
