import { useEffect, useState } from 'react'
import ErrorMessage from '../components/ErrorMessage'
import LoadingState from '../components/LoadingState'
import { moodTuneApi } from '../services/moodTuneApi'

export default function HistoryPage() {
  const [history, setHistory] = useState([]); const [error, setError] = useState(''); const [isLoading, setIsLoading] = useState(true)
  useEffect(() => { moodTuneApi.history().then((response) => setHistory(response.history)).catch((requestError) => setError(requestError.message)).finally(() => setIsLoading(false)) }, [])
  return <section className="content-page"><div className="page-header"><p className="page-eyebrow">Listening journey</p><h1 className="page-title">Recommendation history</h1><p className="page-copy">Look back at the moods, directions, and sessions that shaped your soundtrack.</p></div><ErrorMessage message={error} />{isLoading ? <LoadingState label="Loading your listening history…" /> : history.length ? <ol className="relative space-y-3 before:absolute before:bottom-6 before:left-[1.4rem] before:top-6 before:w-px before:bg-gradient-to-b before:from-lavender-300/50 before:to-transparent">{history.map((record, index) => <li key={`${record.created_at}-${index}`} className="surface relative flex min-w-0 gap-3 p-4 sm:gap-4 sm:p-5"><span className="relative z-[1] mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-full border border-lavender-300/30 bg-lavender-300/[0.1] text-xs text-lavender-200">{index + 1}</span><div className="min-w-0"><p className="break-words font-medium capitalize text-zinc-100">{record.current_mood} <span className="mx-1 text-lavender-300">→</span> {record.target_mood}</p><p className="mt-1 break-words text-sm text-zinc-400">{record.mode === 'feel_better' ? 'Make Me Feel Better' : 'Match My Mood'} <span className="mx-1 text-zinc-700">·</span> {record.track_ids?.length || 0} tracks</p><p className="mt-1.5 break-words text-xs text-zinc-600">{record.created_at ? new Date(record.created_at).toLocaleString() : 'Time unavailable'}</p></div></li>)}</ol> : <p className="empty-state">No recommendation history yet. Your future mood sessions will appear here.</p>}</section>
}
