import { useEffect, useState } from 'react'
import ErrorMessage from '../components/ErrorMessage'
import LoadingState from '../components/LoadingState'
import { moodTuneApi } from '../services/moodTuneApi'

export default function ProfilePage() {
  const [displayName, setDisplayName] = useState(''); const [genres, setGenres] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [isLoading, setIsLoading] = useState(true); const [isSaving, setIsSaving] = useState(false)
  useEffect(() => { moodTuneApi.profile().then((response) => { const profile = response.profile || {}; setDisplayName(profile.display_name || ''); setGenres((profile.preferred_genres || []).join(', ')) }).catch((requestError) => setError(requestError.message)).finally(() => setIsLoading(false)) }, [])
  const save = async (event) => { event.preventDefault(); setError(''); setNotice(''); const preferredGenres = genres.split(',').map((value) => value.trim()).filter(Boolean); if (!displayName.trim()) return setError('Display name is required.'); setIsSaving(true); try { await moodTuneApi.updateProfile({ display_name: displayName.trim(), preferred_genres: preferredGenres }); setNotice('Profile saved.') } catch (requestError) { setError(requestError.message) } finally { setIsSaving(false) } }
  if (isLoading) return <LoadingState label="Loading profile…" />
  return <section className="max-w-xl space-y-6"><div><h1 className="text-3xl font-bold">Profile and preferences</h1><p className="mt-2 text-slate-300">Preferred genres are a supporting signal; they do not override mood matching.</p></div><form onSubmit={save} className="space-y-4 rounded-xl border border-slate-800 bg-slate-900 p-6"><ErrorMessage message={error} />{notice && <p className="text-sm text-emerald-200">{notice}</p>}<label className="block text-sm font-medium">Display name<input value={displayName} onChange={(event) => setDisplayName(event.target.value)} maxLength="80" className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2" /></label><label className="block text-sm font-medium">Preferred genres<p className="mt-1 text-xs font-normal text-slate-400">Separate up to 20 genres with commas.</p><input value={genres} onChange={(event) => setGenres(event.target.value)} placeholder="acoustic, pop, jazz" className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2" /></label><button disabled={isSaving} className="rounded bg-violet-500 px-4 py-2 font-semibold disabled:opacity-60">{isSaving ? 'Saving…' : 'Save profile'}</button></form></section>
}
